# Generated by Django 4.2.1 on 2023-06-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerSide', '0002_alter_friendrequest_from_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='locationX',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='locationY',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='role',
            field=models.BooleanField(default=0),
        ),
    ]
