# Generated by Django 4.2.1 on 2023-06-12 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ServerSide', '0004_guild'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='guild',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guild', to='ServerSide.guild'),
        ),
    ]
