# Generated by Django 4.2.1 on 2023-06-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerSide', '0006_alter_player_guild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, to='ServerSide.player'),
        ),
    ]
