# Generated by Django 4.2.1 on 2023-06-13 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ServerSide', '0008_guild_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Safe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('hp', models.IntegerField(default=100)),
                ('locationX', models.FloatField(default=0.0)),
                ('locationY', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='BreakInEvent',
            fields=[
                ('safe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ServerSide.safe')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='ServerSide.breakinevent'),
        ),
    ]
