# Generated by Django 4.2.1 on 2023-06-21 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ServerSide', '0009_safe_breakinevent_player_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NoNameGuild', max_length=30)),
                ('guildMoney', models.IntegerField(default=0)),
                ('weaponLvl', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RobUnion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NoNameGuild', max_length=30)),
                ('guildMoney', models.IntegerField(default=0)),
                ('machines', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='player',
            name='guild',
        ),
        migrations.RemoveField(
            model_name='player',
            name='friends',
        ),
        migrations.DeleteModel(
            name='Guild',
        ),
        migrations.AddField(
            model_name='player',
            name='policeStation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guild', to='ServerSide.policestation'),
        ),
        migrations.AddField(
            model_name='player',
            name='robUnion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='robUnion', to='ServerSide.robunion'),
        ),
        migrations.AddField(
            model_name='player',
            name='friends',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ServerSide.player'),
        ),
    ]
