# Generated by Django 4.2.1 on 2023-06-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerSide', '0010_policestation_robunion_remove_player_guild_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='friends',
        ),
        migrations.AddField(
            model_name='player',
            name='friends',
            field=models.ManyToManyField(blank=True, to='ServerSide.player'),
        ),
    ]
