# Generated by Django 4.2.1 on 2023-06-21 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ServerSide', '0011_remove_player_friends_player_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='policeStation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='police_station', to='ServerSide.policestation'),
        ),
    ]
