# Generated by Django 4.2.1 on 2023-06-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerSide', '0018_alter_player_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='policeXP',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='robberXP',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='robunion',
            name='hp',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='robunion',
            name='machinesLevels',
            field=models.IntegerField(default=1),
        ),
    ]
