# Generated by Django 4.2.1 on 2023-06-26 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ServerSide', '0019_player_policexp_player_robberxp_robunion_hp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='ServerSide.breakinevent'),
        ),
    ]
