# Generated by Django 4.2.1 on 2023-06-29 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerSide', '0020_alter_player_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakinevent',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 29, 22, 13, 18, 349930)),
        ),
    ]
