# Generated by Django 4.2.1 on 2023-06-29 20:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerSide', '0021_breakinevent_starttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakinevent',
            name='isStarted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='breakinevent',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 29, 22, 33, 59, 846915)),
        ),
    ]
