# Generated by Django 4.2.1 on 2023-06-30 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerSide', '0022_breakinevent_isstarted_alter_breakinevent_starttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='alarmDisabler',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='c4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='breakinevent',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 30, 15, 47, 56, 618674)),
        ),
    ]
