# Generated by Django 4.2.1 on 2023-06-30 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerSide', '0023_player_alarmdisabler_player_c4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakinevent',
            name='alarms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='breakinevent',
            name='c4s',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='policestation',
            name='armorLvl',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='policestation',
            name='hints',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='breakinevent',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 30, 16, 55, 29, 141120)),
        ),
    ]
