# Generated by Django 4.2.1 on 2023-07-03 11:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ServerSide', '0025_alter_breakinevent_safe_alter_breakinevent_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakinevent',
            name='safe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ServerSide.safe'),
        ),
        migrations.AlterField(
            model_name='breakinevent',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 3, 13, 30, 5, 503252)),
        ),
    ]
