# Generated by Django 4.2.1 on 2023-07-03 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerSide', '0026_alter_breakinevent_safe_alter_breakinevent_starttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakinevent',
            name='arrested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='breakinevent',
            name='reward',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='breakinevent',
            name='timeForRobbery',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='safe',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='breakinevent',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 3, 22, 46, 36, 7336)),
        ),
    ]
