# Generated by Django 4.2.1 on 2023-07-04 21:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerSide', '0027_breakinevent_arrested_breakinevent_reward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='safesActive',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='safe',
            name='timePlaced',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 4, 23, 24, 14, 862637)),
        ),
        migrations.AlterField(
            model_name='breakinevent',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 4, 23, 24, 14, 862637)),
        ),
    ]
