# Generated by Django 4.2.1 on 2023-07-06 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerSide', '0028_player_safesactive_safe_timeplaced_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakinevent',
            name='penalty',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='breakinevent',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 22, 3, 34, 941762)),
        ),
        migrations.AlterField(
            model_name='safe',
            name='timePlaced',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 22, 3, 34, 940762)),
        ),
    ]
