# Generated by Django 4.2.1 on 2023-07-09 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerSide', '0030_safe_author_alter_breakinevent_starttime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='safe',
            name='isRobUnion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='breakinevent',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 9, 23, 53, 4, 270449)),
        ),
        migrations.AlterField(
            model_name='safe',
            name='timePlaced',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 9, 23, 53, 4, 270449)),
        ),
    ]
