# Generated by Django 4.2.1 on 2023-07-09 22:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerSide', '0031_safe_isrobunion_alter_breakinevent_starttime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakinevent',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 10, 0, 46, 37, 155208)),
        ),
        migrations.AlterField(
            model_name='breakinevent',
            name='timeForRobbery',
            field=models.FloatField(default=3.0),
        ),
        migrations.AlterField(
            model_name='safe',
            name='timePlaced',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 10, 0, 46, 37, 154209)),
        ),
    ]
