# Generated by Django 4.2.1 on 2023-07-10 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerSide', '0033_player_rotation_alter_breakinevent_starttime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policestation',
            name='robUnionX',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='policestation',
            name='robUnionY',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='breakinevent',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 10, 21, 49, 7, 741706)),
        ),
        migrations.AlterField(
            model_name='safe',
            name='timePlaced',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 10, 21, 49, 7, 740708)),
        ),
    ]
