# Generated by Django 4.2.1 on 2023-07-11 20:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ServerSide', '0035_alter_breakinevent_starttime_alter_player_rotation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakinevent',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 11, 22, 41, 28, 679579)),
        ),
        migrations.AlterField(
            model_name='safe',
            name='author',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='safe',
            name='timePlaced',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 11, 22, 41, 28, 679579)),
        ),
    ]
