# Generated by Django 4.2.1 on 2023-07-11 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerSide', '0036_alter_breakinevent_starttime_alter_safe_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakinevent',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 11, 22, 59, 42, 112445)),
        ),
        migrations.AlterField(
            model_name='safe',
            name='isRobUnion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='safe',
            name='timePlaced',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 11, 22, 59, 42, 111444)),
        ),
    ]
