# Generated by Django 4.2.1 on 2023-07-15 19:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ServerSide', '0038_policestation_robunionsafeid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakinevent',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 15, 21, 56, 21, 849052)),
        ),
        migrations.AlterField(
            model_name='safe',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placed_safes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='safe',
            name='timePlaced',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 15, 21, 56, 21, 848052)),
        ),
    ]
